### ISSUE TITLE
Recurring Events Manager add-on

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-recurring-events-manager#1]
The plan is to start with an MVP of the REM by creating a standalone REM admin interface.

MVP Outline:
the first 4 things that need to be done are:
1) find all existing tickets and make a list of them with links
2) get images/screenshots of existing REM type UIs
3) define an MVP (the least functionality we can get away with)
4) define detailed use cases for the above MVP

Feature planning discussion:
http://p2.eventespresso.com/2015/11/17/feature-planning-recurring-events-add-on/

Full Integration with the event editor requires the completion of: 
https://trello.com/c/6s2QieO4/616-update-add-on-skeleton-with-new-ddd-structure
https://trello.com/c/Ukq1mPwA/480-event-editor-improvements

Additional Feature Ideas

- [ ] Group Recurring Events in the Event List and API
- [ ] Quick Edit (ability to quickly edit titles, tags, categories, etc) for multiple events
- [ ] Ability to register for a series of recurring events all at once
- [ ] Exclude recurring events using shortcode parameter
- [ ] Ability to apply discount codes to a series of events
- [ ] Ability to show one event in series but us a date selector to register
 
Related Tickets

- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/81
- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/771
- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/1620
- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/11373

Old Tickets

- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/1513
- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/2130
- [ ] https://events.codebasehq.com/projects/event-espresso/tickets/4874

References

- [ ] https://eventespresso.com/topic/distillery-tours/
- [ ] https://eventespresso.com/topic/some-ideas-for-the-rem/
- [ ] https://eventespresso.com/topic/recurring-events-in-ee4-calendar/
- [ ] https://eventespresso.com/topic/venues-recurring-events-and-ticket-sales/#post-137955
- [ ] https://eventespresso.com/topic/recurring-events-in-ee4-2/
- [ ] https://eventespresso.com/product/espresso-recurring/
- [ ] https://eventespresso.com/forum/recurring-events-manager/
- [ ] https://eventespresso.com/wiki/recurring-events-manager-add-on/
- [ ] https://eventespresso.com/wiki/recurring-events-dropdown-template-add-on/

Seth Shoultes Aug 25, 2017 at 11:00 AM
Josh mentioned this in chat:

I wonder about that add-on because it seems there’s not a clear path whether each recurring event should be its own WP event post, or should the whole series be one event post.

I think for SEO purposes it may be better to publish one post on the front end. The backend will need some tweaking to accommodate all those different registration lists.
